spring.application.name=boardinghouse

spring.datasource.url=jdbc:postgresql://db.iitpvyeasouzxclsemnz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Ferrater_24
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true